-- 코드를 입력하세요
SELECT A.CATEGORY, A.PRICE AS MAX_PRICE, A.PRODUCT_NAME FROM FOOD_PRODUCT A,
(SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
GROUP BY CATEGORY) AS X
WHERE A.PRICE = X.MAX_PRICE AND A.CATEGORY = X.CATEGORY
AND A.CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY PRICE DESC;
